"""create cameras

Revision ID: a43b43e08e6b
Revises: 
Create Date: 2026-10-08 10:36:09.715911
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'a43b43e08e6b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('assigned_worker', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("source_type IN ('file', 'rtsp', 'mock')", name=op.f('ck_cameras_source_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cameras'))
    )
    op.create_index('uq_cameras_name_active', 'cameras', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_cameras_name_active', table_name='cameras', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('cameras')
    # ### end Alembic commands ###
